config/routes.rb
Rails.application.routes.draw do
  
  get 'programming/login_check'
  root 'programming#index'
  get 'programming', to: 'programming#index'
  get 'programming/add' 
  get 'programming/find', to: 'programming#find'
  post 'programming/find', to: 'programming#find'
  post 'programming/add', to: 'programming#create'
  get 'programming/edit/:id', to: 'programming#edit'
  post 'programming/edit/:id', to: 'programming#update'
  patch 'programming/edit/:id', to: 'programming#update'
  get 'programming/delete/:id', to: 'programming#delete'
  get 'programming/:id', to: 'programming#show'
  devise_for :accounts
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

end

app/models/account.rb
class Account < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  has_many :programming 
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/programming.rb
class Programming < ApplicationRecord
    belongs_to :account 
    validates :title, presence: true
    validates :question, presence: true
    validates :account_id, presence: true
    
        def self.search(search) #self.でクラスメソッドとしている
          if search # Controllerから渡されたパラメータが!= nilの場合は、titleカラムを部分一致検索
            Programming.where(['title LIKE ?', "%#{search}%"])
          else
            Programming.all #全て表示。
          end
        end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/programming_controller.rb
class ProgrammingController < ApplicationController
    before_action :authenticate_account!, only: [:login_check, :show, :new ,:edit ,:add]

    def login_check
        @account = current_account
        @msg = 'you logined at: '+ @account.current_sign_in_at.to_s
    end

   def index
    if current_account 
        @programming = current_account.programming.page params[:page]
    else
        @programming = Programming.page params[:page]
    end
   end

   def show
    @programming = current_account.programming.find(params[:id])
   end

   def add
     @programming = current_account.programming.new
   end

   def create
    if request.post? then
        ogj = current_account.programming.create(programming_params)
    end
    redirect_to '/programming'
   end
   
   def edit
    @programming = Programming.find(params[:id])
   end

   def update
    obj = Programming.find(params[:id])
    obj.update(programming_params)
    redirect_to '/programming'   
   end

   def delete
    Programming.find(params[:id]).destroy
    redirect_to '/programming'
   end

   def find
    #ViewのFormで取得したパラメータをモデルに渡す
    if current_account 
        @programming = current_account.programming.page.search(params[:search])
    else
        @programming = Programming.page.search(params[:search])
    end
   end

    private
    def programming_params
        params.require(:programming).permit(:account_id, :title, :question, :answer, :url)
    end   
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/programming_helper.rb
module ProgrammingHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProgrammingErrorApp</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/programming">Programming Error App</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="/programming">Home <span class="sr-only">(current)</span></a>
      </li>
      <% if current_account %>
      <li class="nav-item">
        <a class="nav-link" href="/programming/add">New </a>
      </li>
      <% end %>
      <li class="nav-item"> 
      <% if current_account.nil? %>
        <%= link_to 'go to login_check page!' .html_safe,new_account_session_path, :class=>"nav-link" %>    
        <% else %>
        <%= link_to "sign out" .html_safe, destroy_account_session_path, method: :delete, :class=>"nav-link"%>
        <%end%>
      </li>
      <li class="nav-item">
        <% if current_account %>
          <span class="navbar-text"><%= "ようこそ！#{current_account.email}さん！"%></span>
        <%end%>
      </li>
    </ul>
    <%= form_tag controller: "/programming", action: "find" do %>
      <div class="form-inline my-2 my-lg-0">
          <%= text_field_tag :search, params[:search],{class: "form-control mr-sm-2"} %>
          <%= submit_tag "Search", :name => nil, :class => "btn btn-outline-success my-2 my-sm-0" %>
      </div>
    <% end %>
    

    
    
</nav>
<div class="container">
    <%= yield %>

 </div>
  <div class="card-footer">
    <small class="text-muted">Created by sumiya</small>
  </div>
    </body>
</html>

app/views/programming/add.html.erb
    <%= form_for(@programming, url:{controller:'programming', action:'create'}) do |form|%>
        <div class="form-group">
            <tr>
                <th>タイトル</th>
                <td>
                    <%= form.text_field :title, size: 100 , :class=>'form-control'%>
                </td>
            </tr>
        </div>
        <div class="form-group">
            <tr>
                <th>エラー</th>
                <td>
                    <%= form.text_field :question, size: 100, :class=>'form-control' %>
                </td>
            </tr>
        </div>
        <div class="form-group">
            <tr>
                <th>解決策</th>
                <td>
                    <%= form.text_field :answer, size: 100, :class=>'form-control' %>
                </td>
            </tr>
        </div>
        <div class="form-group">
            <tr>
                <th>参考リンク</th>
                <td>
                    <%= form.text_field :url , size: 100, :class=>'form-control' %>
                </td>
            </tr>
        </div>
        <div>
            <tr>
                <th></th>
                <td>
                    <%= form.submit "送信" , :class=>"btn btn-primary"%>
            </tr>
        </div>
        <%end%>

app/views/programming/edit.html.erb
     <%= form_for(@programming, url:{controller:'programming', action:'update', id:@programming.id}) do |form|%>
            <div class="form-group">
                <tr>
                    <th>タイトル</th>
                    <td>
                        <%= form.text_field :title , size: 100, :class=>'form-control'%>
                    </td>
                </tr>
            </div>
            <div class="form-group">
                <tr>
                    <th>エラー</th>
                    <td>
                        <%= form.text_field :question, size: 100, :class=>'form-control' %>
                    </td>
                </tr>
            </div>
            <div class="form-group">
                <tr>
                    <th>解決策</th>
                    <td>
                        <%= form.text_field :answer, size: 100, :class=>'form-control' %>
                    </td>
                </tr>
            </div>
            <div class="form-group">
                <tr>
                    <th>参照リンク</th>
                    <td>
                        <%= form.text_field :url , size: 100, :class=>'form-control' %>
                    </td>
                </tr>
            </div>
            <div>
                <tr>
                    <th></th>
                    <td>
                        <%= form.submit "送信" , size: 100, :class=>"btn btn-primary"%>
                </tr>
            </div>
            <%end%>

app/views/programming/find.html.erb
<div class="table-responsive">
<table class="table table-bordered">
    <thead class="thead-dark"> 
        <tr>
            <th>タイトル</th><th>エラー</th><th>解決策</th><th>参考リンク</th>
            <% if current_account %>
                <th></th><th></th>
                <%end%>
        </tr>
    </thead>
    <tbody>
        <% @programming.each do |obj| %>
        <tr>
            <td><a href="/programming/<%= obj.id%>"><%= obj.title %></a></td>
            <td><%= obj.question %></td>
            <td><%= obj.answer %></td>
            <td><%= obj.url %></td>
            <% if current_account %>
            <td><a href="/programming/edit/<%= obj.id%>">編集</a></td>
            <td><a href="javascript:window.delData(
                <%= (obj.id.to_s + " , '".to_s + obj.title.to_s).html_safe %>'); ">削除</a></td>
                <%end%>
        </tr>
    </tbody>
        <% end %>
</table>
</div>
<div class="paginate"><%= paginate @programming %></div>

app/views/programming/index.html.erb
<div class="message_area">
<h1>エラーメッセージと解決方法一覧。</h1>
<h3>エラーメッセージの解決方法や参考URLを掲載しています。</h3>
</div>
<div class="table-responsive">
<table class="table table-bordered">
    <thead class="thead-dark"> 
        <tr>
            <th>タイトル</th><th>エラー</th><th>解決策</th><th>参考リンク</th>
            <% if current_account %>
                <th></th><th></th>
                <%end%>
        </tr>
    </thead>
    <tbody>
        <% @programming.each do |obj| %>
        <tr>
            <td><a href="/programming/<%= obj.id%>"><%= obj.title %></a></td>
            <td><%= obj.question %></td>
            <td><%= obj.answer %></td>
            <td><%= obj.url %></td>
            <% if current_account %>
            <td><a href="/programming/edit/<%= obj.id%>">編集</a></td>
            <td><a href="javascript:window.delData(
                <%= (obj.id.to_s + " , '".to_s + obj.title.to_s).html_safe %>'); ">削除</a></td>
                <%end%>
        </tr>
    </tbody>
        <% end %>
</table>
</div>
<div class="paginate"><%= paginate @programming %></div>

app/views/programming/login_check.html.erb
<h1>
    <%= @account.email %>
</h1>
<p>
    <%= @msg %>
</p>

app/views/programming/show.html.erb
<div class="message_area">
<h1>ここには質問の詳細を掲載します。</h1>
</div>
<table class="table table-bordered">
  <thead class="thead-dark">
    <tr><th>タイトル</th>
        <td><%= @programming.title %></td></tr>
    <tr><th>エラー</th>
        <td><%= @programming.question %></td></tr>
    <tr><th>解決策</th>
        <td><%= @programming.answer %></td></tr>
    <tr><th>参照リンク</th>
        <td><%= @programming.url %></td></tr>
    </tbody>
</table>